---
kind: pipeline
name: default


steps:
- name: test
  image: python
  commands:
  - cd example
  - pip install -r requirements-dev.txt
  - coverage run -m pytest
  - coverage report -m
  - coverage html

