---
kind: pipeline
name: default


steps:
- name: test
  image: python
  commands:
  - cd example
  - pip install -r requirements-dev.txt
  - coverage run -m pytest
  - coverage report -m
  - coverage html
- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_bot_token
    to:
      from_secret: telegram_chat_id
