---
kind: pipeline
name: default

steps:
- name: test
  image: python
  extra_hosts: 
    - "git.ops.dev:172.21.0.1"
  commands:
  - cd example
  - pip install pipenv
  - pipenv install
  - pipenv run coverage run --source=. -m pytest
  - pipenv run coverage report -m
  - pipenv run coverage html

