---
kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - ping -c3 git.ops.dev 
  - cd example
  - pip install pipenv
  - pipenv install
  - pipenv run coverage run --source=. -m pytest
  - pipenv run coverage report -m
  - pipenv run coverage html

