version: '3'

services:
  proxy:
    image: traefik:v2.4
    command: --api --providers.docker --providers.docker.exposedbydefault=false --providers.file.directory=/etc/traefik --providers.file.watch=true --entrypoints.websecure.address=:443 --entrypoints.websecure.http.tls=true
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`proxy.edersohe.dev`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.rule=Host(`proxy.edersohe.dev`)"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.edersohe.dev`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
  git:
    image: gitea/gitea:1.14
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./gitea:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.git.rule=Host(`git.edersohe.dev`)"
      - "traefik.http.services.git.loadbalancer.server.port=3000"
  ci:
    image: drone/drone:2
    restart: always
    environment:
      - DRONE_GITEA_SERVER=https://git.edersohe.dev
      - DRONE_GITEA_CLIENT_ID=e2f83605-298e-4e68-abb3-50fa82f1be77
      - DRONE_GITEA_CLIENT_SECRET=q_HuJyVUIdPjn8dDgn8y2TWaTfIbI-YE3YRs0G_qR04=
      - DRONE_GITEA_SKIP_VERIFY=true
      - DRONE_RPC_SECRET=e900d9cf1ad5feff8fcc30da29798af2
      - DRONE_SERVER_HOST=ci.edersohe.dev
      - DRONE_SERVER_PROTO=https
      - DRONE_REGISTRATION_CLOSED=true
    volumes:
      - ./drone:/data
      - ./traefik/certs:/etc/certs 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ci.rule=Host(`ci.edersohe.dev`)"
      - "traefik.http.services.ci.loadbalancer.server.port=80"
    extra_hosts:
      - "git.edersohe.dev:172.21.0.1"
  runner:
    image: drone/drone-runner-docker:1
    restart: always
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=ci
      - DRONE_RPC_SECRET=e900d9cf1ad5feff8fcc30da29798af2
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=runner
      - DRONE_UI_USERNAME=root
      - DRONE_UI_PASSWORD=root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.runner.rule=Host(`runner.edersohe.dev`)"
      - "traefik.http.services.runner.loadbalancer.server.port=3000"

